fixed generating random numbers
For instance, DataFactory#getNumber() method throws IllegalArgumentException: n must be positive, so this commit passes absolute values of argument substraction.

Stack trace:

java.lang.IllegalArgumentException: n must be positive
	at java.util.Random.nextInt(Random.java:300)
	at org.fluttercode.datafactory.impl.DataFactory.getNumberBetween(DataFactory.java:320)
	at org.fluttercode.datafactory.impl.DataFactory.getNumber(DataFactory.java:289)